name: Deploy to HF Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/UniversalWarrior48/AI_TEST space
          rsync -av --exclude .git ./ space/
          cd space
          git add .
          git config --global user.email "universalwarrior48@gmail.com"
          git config --global user.name "Sagar Pohekar"
          git commit -m "Deploy from GitHub"
          git push https://$HF_TOKEN@huggingface.co/spaces/UniversalWarrior48/AI_TEST main